version: '3.8'
services:
  mysql:
    container_name: compedia_mysql
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=centwong
    restart: on-failure
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume: