DROP TABLE IF EXISTS `university`;
CREATE TABLE IF NOT EXISTS `university`(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255)
) ENGINE = INNODB;

INSERT INTO `university`(name)
VALUES
    ('Akademi Farmasi Mitra Sehat Mandiri Sidoarjo'),
    ('Institut Sains & Teknologi Akprind'),
    ('STMIK AMIKOM Yogyakarta'),
    ('STIKES RS Anwar Medika'),
    ('Universitas Katolik Indonesia Atma Jaya'),
    ('Universitas Bakrie'),
    ('Binus University'),
    ('STIKES Bina Sehat PPNI Mojokerto'),
    ('Universitas Bung Hatta'),
    ('Universitas Dian Nuswantoro'),
    ('Universitas Gunadarma'),
    ('Universitas Ibn Chaldun Jakarta'),
    ('Universitas Indonusa Esa Unggul'),
    ('Bogor Agricultural University'),
    ('Institut Sains dan Teknologi Al Kamal'),
    ('Institut Teknologi Adhi Tama Surabaya'),
    ('Institut Teknologi Bandung'),
    ('Institut Teknologi Sepuluh Nopember'),
    ('Universitas Janabadra'),
    ('Universitas Jayabaya'),
    ('Universitas Ma Chung'),
    ('Universitas Maarif Hasyim Latif'),
    ('Universitas Mahendradatta'),
    ('Universitas Negeri Malang'),
    ('Universitas Kristen Maranatha'),
    ('Universitas Mercu Buana'),
    ('Universitas Dr. R. Moestopo'),
    ('Universitas Narotama'),
    ('Universitas HKBP Nommensen'),
    ('Universitas Pembangunan Panca Budi'),
    ('Universitas Paramadina Mulya'),
    ('Universitas Nasional Pasim'),
    ('STIE Perbanas'),
    ('Perbanas Institute'),
    ('Universitas Kristen Petra'),
    ('Prasetiya Mulya Business School'),
    ('Politeknik Negeri Jakarta'),
    ('Politeknik Negeri Lhokseumawe'),
    ('Politeknik Negeri Bandung'),
    ('Politeknik Negeri Semarang'),
    ('Politeknik Negeri Padang'),
    ('Politeknik Negeri Pontianak'),
    ('Politeknik Negeri Malang'),
    ('Politeknik Pos Indonesia'),
    ('Politeknik Negeri Sambas'),
    ('Universitas Putera Batam'),
    ('Universitas Sarjanawiyata Tamansiswa'),
    ('Swiss German University'),
    ('STMIK Sinar Nusantara'),
    ('Sekolah Tinggi Akuntansi Negara (STAN)'),
    ('Trisakti Institute of Tourism'),
    ('Universitas Telkom'),
    ('Universitas Klabat'),
    ('Universitas Trisakti'),
    ('Universitas Ahmad Dahlan'),
    ('Universitas Atma Jaya Yogyakarta'),
    ('Universitas Brawijaya'),
    ('Universitas Surabaya'),
    ('Universitas Bhayangkara Surabaya'),
    ('Universitas Bhayangkara Jakarta Raya'),
    ('Universitas Bunda Mulia Jakarta'),
    ('Universitas Darma Agung'),
    ('Universitas Gadjah Mada'),
    ('Universitas Indonesia'),
    ('Universitas Islam Indonesia'),
    ('Universitas Ibn Khaldun Bogor'),
    ('Universitas Islam Jakarta'),
    ('Universitas Islam Riau'),
    ('Universitas Islam Sumatera Utara'),
    ('Universitas Kristen Duta Wacana'),
    ('Universitas Kristen Indonesia'),
    ('Universitas Kristen Indonesia Tomohon'),
    ('Universitas Kristen Krida Wacana'),
    ('Universitas Kristen Satya Wacana'),
    ('Universitas Muslim Indonesia'),
    ('Universitas Methodist Indonesia'),
    ('Universitas Muhammadiyah Jakarta'),
    ('Universitas Muria Kudus'),
    ('Universitas Muhammadiyah Malang'),
    ('Universitas Muhammadiyah Magelang'),
    ('Universitas Muhammadiyah Sidoarjo'),
    ('Universitas Muhammadiyah Surakarta'),
    ('Universitas Muhammadiyah Sumatra Utara'),
    ('Universitas Muhammadiyah Yogyakarta'),
    ('Universitas Advent Indonesia'),
    ('Universitas Airlangga'),
    ('Universitas Andalas'),
    ('Universitas Nasional Jakarta'),
    ('Universitas Cenderawasih'),
    ('Universitas Nusa Cendana'),
    ('Universitas Diponegoro'),
    ('Universitas Jember'),
    ('Universitas Negeri Surabaya'),
    ('Universitas Negeri Gorontalo'),
    ('Universitas Haluoleo'),
    ('Universitas Amir Hamzah'),
    ('Universitas Hasanuddin'),
    ('Universitas Bengkulu'),
    ('Universitas Bojonegoro'),
    ('Universitas Katolik Soegijapranoto'),
    ('Universitas Pekalongan'),
    ('Universitas Kediri'),
    ('Universitas Komputer Indonesia'),
    ('Universitas Lampung'),
    ('Universitas Lancang Kuning'),
    ('Universitas Negeri Manado'),
    ('Universitas Negeri Medan'),
    ('Universitas Islam Nusantara'),
    ('Universitas Pesantren Darul Ulum Jombang'),
    ('Universitas Madura'),
    ('Universitas Islam Bandung'),
    ('Universitas Islam Malang'),
    ('Universitas Muhammadiyah Makassar'),
    ('Universitas Slamet Riyadi Surakarta'),
    ('Universitas Islam Sultan Agung'),
    ('Universitas Islam Syekh-Yusuf'),
    ('Unitomo Surabaya'),
    ('Universitas Trilogi'),
    ('Universitas Trunojoyo Madura'),
    ('Universitas Pancasila'),
    ('Universitas PGRI Adi Buana Surabaya'),
    ('Universitas Jambi'),
    ('Universitas Negeri Jakarta'),
    ('Universitas Jenderal Achmad Yani'),
    ('Universitas Khairun'),
    ('Universitas Krisnadwipayana'),
    ('Universitas Lambung Mangkurat'),
    ('Universitas Negeri Makassar'),
    ('Universitas Mahasaraswati Denpasar'),
    ('Universitas Merdeka Malang'),
    ('Universitas Merdeka Madiun'),
    ('Universitas Muhammadiyah Jember'),
    ('Universitas Muhammadiyah Mataram'),
    ('Universitas Mulawarman'),
    ('STMIK Widya Cipta Dharma'),
    ('Universitas Negeri Semarang'),
    ('Universitas Negeri Padang'),
    ('Universitas Padjadjaran'),
    ('Universitas Pakuan'),
    ('Universitas Katolik Parahyangan'),
    ('Universitas Pasundan'),
    ('Universitas Pattimura'),
    ('Universitas Ngurah Rai'),
    ('Universitas Mataram'),
    ('Universitas Riau'),
    ('Universitas Sebelas Maret'),
    ('Universitas Darma Persada'),
    ('Universitas Siliwangi'),
    ('Universitas Jenderal Soedirman'),
    ('Universitas Sam Ratulangi'),
    ('Universitas Sriwijaya'),
    ('Universitas Swadaya Gunung Djati'),
    ('Universitas Syiah Kuala'),
    ('Universitas Tadulako'),
    ('Universitas 17 Agustus 1945 Surabaya'),
    ('Universitas 17 Agustus 1945 Banyuwangi'),
    ('Universitas 17 Agustus 1945 Cirebon'),
    ('Universitas 17 Agustus 1945 Jakarta'),
    ('Universitas 17 Agustus 1945 Samarinda'),
    ('Universitas 17 Agustus 1945 Semarang'),
    ('Universitas Tanjungpura'),
    ('Universitas Tarumanagara'),
    ('Universitas Sultan Ageng Tirtayasa'),
    ('Universitas Udayana'),
    ('Universitas Wijaya Kusuma Purwokerto'),
    ('Universitas Negeri Yogyakarta'),
    ('Universitas Proklamasi 45'),
    ('Universitas Pelita Harapan'),
    ('Universitas Pendidikan Indonesia'),
    ('Universitas Pembangunan Nasional Veteran Jakarta'),
    ('Universitas Pembangunan Nasional Veteran Jawa Timur'),
    ('Universitas Pembangunan Nasional Veteran Yogyakarta'),
    ('Universitas Palangka Raya'),
    ('Universitas Pancasakti Tegal'),
    ('Universitas Sanata Dharma'),
    ('Universitas Simalungun'),
    ('Universitas Semarang'),
    ('Universitas Sumatera Utara'),
    ('Universitas Terbuka Indonesia'),
    ('Universitas Tidar Magelang'),
    ('Universitas Tunas Pembangunan'),
    ('Universitas Widya Gama Malang'),
    ('Universitas Katolik Widya Karya'),
    ('Universitas Widyatama'),
    ('Universitas Wijaya Kusuma Surabaya'),
    ('Universitas Katolik Widya Manadala'),
    ('Universitas Wisnuwardhana'),
    ('Universitas Persada Indonesia Y.A.I'),
    ('Universitas Yarsi'),
    ('Duta Bangsa University'),
    ('Akademi Farmasi Yarsis Pekanbaru');
